name: 'Greetings'

on:
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Awesome work, @${{ github.actor }}! 🎉 Thank you for your contribution and efforts to enhance Hairify. 

            Please don't tag the maintainers, we will review your changes soon and provide feedback.

            
          footer: 'Please ensure that you have followed the contributing guidelines for a smooth review process.'